@startuml
class PlayerNameLabelConverter {
    + Convert(values:IList<object?>, targetType:Type, parameter:object?, culture:CultureInfo) : object?
    + ConvertBack(value:object?, targetTypes:Type[], parameter:object?, culture:CultureInfo) : object?[]
}
IMultiValueConverter <|-- PlayerNameLabelConverter
@enduml
